package icons;

import com.intellij.openapi.util.IconLoader;

import javax.swing.*;

/**
 * NOTE THIS FILE IS AUTO-GENERATED by the build/scripts/icons.gant
 * Don't repeat mistakes of others ;-)
 */
public class TFSIcons {
  private static Icon load(String path) {
    return IconLoader.getIcon(path, TFSIcons.class);
  }

  public static final Icon Teamserver = load("/icons/teamserver.gif"); // 16x16
}
