// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license. See License.txt in the project root.

package com.microsoft.alm.plugin.idea.tfvc.ui.servertree;

import com.intellij.ide.DataManager;
import com.intellij.openapi.Disposable;
import com.intellij.openapi.actionSystem.ActionPlaces;
import com.intellij.openapi.actionSystem.DataKey;
import com.intellij.openapi.actionSystem.DataProvider;
import com.intellij.openapi.util.Condition;
import com.intellij.openapi.util.Disposer;
import com.intellij.ui.PopupHandler;
import com.intellij.ui.TreeSpeedSearch;
import com.intellij.ui.components.JBScrollPane;
import com.intellij.ui.treeStructure.Tree;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import com.intellij.util.EventDispatcher;
import com.intellij.util.ui.EmptyIcon;
import com.intellij.util.ui.UIUtil;
import com.microsoft.alm.plugin.context.ServerContext;
import org.jetbrains.annotations.NonNls;
import org.jetbrains.annotations.Nullable;

import javax.swing.Icon;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.event.TreeSelectionEvent;
import javax.swing.event.TreeSelectionListener;
import javax.swing.tree.TreeSelectionModel;
import java.awt.Dimension;
import java.awt.Insets;
import java.util.EventListener;
import java.util.Set;

public class TfsTreeForm implements Disposable, DataProvider {
    private boolean canCreateVirtualFolders;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new GridLayoutManager(3, 1, new Insets(0, 0, 0, 0), -1, -1));
        final JBScrollPane jBScrollPane1 = new JBScrollPane();
        contentPane.add(jBScrollPane1, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        tree = new Tree();
        jBScrollPane1.setViewportView(tree);
        pathField = new JTextField();
        pathField.setEditable(false);
        contentPane.add(pathField, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        messagePanel = new JPanel();
        messagePanel.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        contentPane.add(messagePanel, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        messagePanel.add(spacer1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_CAN_GROW, null, new Dimension(11, 10), null, 0, false));
        messageLabel = new JLabel();
        messageLabel.setText("Label");
        messagePanel.add(messageLabel, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }


    public interface SelectionListener extends EventListener {
        void selectionChanged();
    }

    public static class SelectedItem {
        public final String path;
        public final boolean isDirectory;

        public SelectedItem(final String path, final boolean idDirectory) {
            this.path = path;
            isDirectory = idDirectory;
        }

        public SelectedItem(final TfsTreeNode treeNode) {
            this(treeNode.getPath(), treeNode.isDirectory());
        }
    }

    public static final DataKey<TfsTreeForm> KEY = DataKey.create("TfsTreeForm");
    public static final String POPUP_ACTION_GROUP = "TfvcTreePopupMenu";
    public static final Icon EMPTY_ICON = new EmptyIcon(0, UIUtil.getBalloonWarningIcon().getIconHeight());

    private JComponent contentPane;
    private Tree tree;
    private JTextField pathField;
    private JLabel messageLabel;
    private JPanel messagePanel;
    private TfsTreeBuilder treeBuider;
    private EventDispatcher<SelectionListener> eventDispatcher = EventDispatcher.create(SelectionListener.class);
    private SelectedItem selectedItem; // have to cache selected item to be available after form is disposed

    public TfsTreeForm() {
        DataManager.registerDataProvider(tree, this);
        new TreeSpeedSearch(tree);
        tree.getSelectionModel().setSelectionMode(TreeSelectionModel.SINGLE_TREE_SELECTION);
        tree.getSelectionModel().addTreeSelectionListener(new TreeSelectionListener() {
            public void valueChanged(TreeSelectionEvent e) {
                selectedItem = doGetSelectedItem();
                pathField.setText(selectedItem != null ? selectedItem.path : null);
                eventDispatcher.getMulticaster().selectionChanged();
            }
        });
        PopupHandler.installPopupHandler(tree, POPUP_ACTION_GROUP, ActionPlaces.REMOTE_HOST_DIALOG_POPUP);
        setMessage(null, false);
    }

    @Nullable
    public SelectedItem getSelectedItem() {
        return selectedItem;
    }

    @Nullable
    public String getSelectedPath() {
        return selectedItem != null ? selectedItem.path : null;
    }

    @Nullable
    private SelectedItem doGetSelectedItem() {
        final Set<Object> selection = treeBuider.getSelectedElements();
        if (selection.isEmpty()) {
            return null;
        }

        final Object o = selection.iterator().next();
        return o instanceof TfsTreeNode ? new SelectedItem(((TfsTreeNode) o)) : null;
    }

    public void initialize(final ServerContext serverContext,
                           @Nullable final String initialSelection,
                           final boolean foldersOnly,
                           final boolean canCreateVirtualFolders,
                           @Nullable final Condition<String> pathFilter) {
        this.canCreateVirtualFolders = canCreateVirtualFolders;
        final TfsTreeNode root = new TfsTreeNode(tree, serverContext, initialSelection, foldersOnly, pathFilter);
        treeBuider = TfsTreeBuilder.createInstance(root, tree);
        Disposer.register(this, treeBuider);

        final TfsTreeNode selection = root.createForSelection(initialSelection);
        if (selection != null) {
            treeBuider.select(selection);
        }
    }

    public void addListener(SelectionListener selectionListener) {
        eventDispatcher.addListener(selectionListener, this);
    }

    public JComponent getContentPane() {
        return contentPane;
    }

    public JComponent getPreferredFocusedComponent() {
        return tree;
    }

    @Override
    public void dispose() {
    }

    @Override
    public Object getData(@NonNls final String dataId) {
        if (KEY.is(dataId)) {
            return this;
        }
        return null;
    }

    public void createVirtualFolder(final String folderName) {
        final Set<Object> selection = treeBuider.getSelectedElements();
        if (selection.isEmpty()) {
            return;
        }

        final Object o = selection.iterator().next();
        if (!(o instanceof TfsTreeNode)) {
            return;
        }
        final TfsTreeNode treeNode = (TfsTreeNode) o;
        final TfsTreeNode child = treeNode.createVirtualSubfolder(folderName);
        treeBuider.queueUpdateFrom(treeNode, true).doWhenDone(new Runnable() {
            @Override
            public void run() {
                treeBuider.select(child);
            }
        });
    }

    public boolean canCreateVirtualFolders() {
        return canCreateVirtualFolders;
    }

    public void setMessage(final String text, final boolean error) {
        if (text != null) {
            messagePanel.setVisible(true);
            messageLabel.setText(text);
            messageLabel.setIcon(error ? UIUtil.getBalloonWarningIcon() : EMPTY_ICON);
        } else {
            messagePanel.setVisible(false);
        }
    }
}
