// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license. See License.txt in the project root.

package com.microsoft.alm.plugin.idea.ui.pullrequest;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.microsoft.alm.plugin.idea.resources.TfPluginBundle;

import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JToolBar;
import javax.swing.JTree;
import java.awt.Dimension;
import java.awt.Insets;
import java.awt.event.ActionListener;
import java.util.Date;
import java.util.ResourceBundle;

public class VcsPullRequestsForm {
    //controls
    private JPanel tabPanel;
    private JTree pullRequestsTree;
    private JToolBar actionsToolbar;
    private JLabel statusLabel;
    private JButton addButton;
    private JButton refreshButton;

    //commands
    public static final String CMD_REFRESH = "refresh";
    public static final String CMD_CREATE_NEW_PULL_REQUEST = "createNewPullRequest";

    private boolean initialized = false;
    private Date lastRefreshed;

    public JComponent getPanel() {
        ensureInitialized();
        return tabPanel;
    }

    private void ensureInitialized() {
        if (!initialized) {
            pullRequestsTree.setCellRenderer(new PullRequestsTreeModel.PRTreeCellRenderer());
            pullRequestsTree.setRootVisible(false);

            addButton.setActionCommand(CMD_CREATE_NEW_PULL_REQUEST);
            refreshButton.setActionCommand(CMD_REFRESH);
            this.initialized = true;
        }
    }

    public void setLoading(final boolean loading) {
        updateStatusText(true, loading);
    }

    public void setConnected(final boolean connected) {
        updateStatusText(connected, false);
    }

    private void updateStatusText(final boolean connected, final boolean loading) {
        if (!connected) {
            statusLabel.setText(TfPluginBundle.message(TfPluginBundle.KEY_VCS_PR_NOT_CONNECTED));
        }

        if (connected && loading) {
            //Loading in progress
            statusLabel.setText(TfPluginBundle.message(TfPluginBundle.KEY_VCS_PR_LOADING));
        }

        if (connected && !loading) {
            //loading complete
            if (lastRefreshed == null) {
                lastRefreshed = new Date();
            }
            statusLabel.setText(TfPluginBundle.message(TfPluginBundle.KEY_VCS_PR_LAST_REFRESHED_AT, lastRefreshed.toString()));
        }
    }

    public void setLastRefreshed(final Date lastRefreshed) {
        this.lastRefreshed = lastRefreshed;
    }

    public void setPullRequestsTree(final PullRequestsTreeModel treeModel) {
        pullRequestsTree.setModel(treeModel);
    }

    public void addActionListener(final ActionListener listener) {
        addButton.addActionListener(listener);
        refreshButton.addActionListener(listener);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        tabPanel = new JPanel();
        tabPanel.setLayout(new GridLayoutManager(3, 1, new Insets(0, 0, 0, 0), -1, -1));
        actionsToolbar = new JToolBar();
        actionsToolbar.setFloatable(false);
        tabPanel.add(actionsToolbar, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(-1, 20), null, 0, false));
        addButton = new JButton();
        addButton.setBorderPainted(false);
        addButton.setIcon(new ImageIcon(getClass().getResource("/general/add.png")));
        addButton.setText("");
        addButton.setToolTipText(ResourceBundle.getBundle("com/microsoft/alm/plugin/idea/ui/tfplugin").getString("Actions.CreatePullRequest.Message"));
        actionsToolbar.add(addButton);
        refreshButton = new JButton();
        refreshButton.setBorderPainted(false);
        refreshButton.setIcon(new ImageIcon(getClass().getResource("/actions/refresh.png")));
        refreshButton.setOpaque(false);
        refreshButton.setText("");
        refreshButton.setToolTipText(ResourceBundle.getBundle("com/microsoft/alm/plugin/idea/ui/tfplugin").getString("CheckoutDialog.RefreshButton.ToolTip"));
        actionsToolbar.add(refreshButton);
        statusLabel = new JLabel();
        statusLabel.setText("Label");
        tabPanel.add(statusLabel, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JScrollPane scrollPane1 = new JScrollPane();
        tabPanel.add(scrollPane1, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        pullRequestsTree = new JTree();
        scrollPane1.setViewportView(pullRequestsTree);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return tabPanel;
    }
}
